apiVersion: v2
name: metallb
description: The Metal LB for Kubernetes
version: 2.0.2
appVersion: 0.9.5
home: https://github.com/bitnami/charts/tree/master/bitnami/metallb
icon: https://bitnami.com/assets/stacks/metallb-speaker/img/metallb-speaker-stack-220x234.png
keywords:
  - load-balancer
  - balancer
  - lb
  - bgp
  - arp
  - vrrp
  - vip
sources:
  - https://github.com/metallb/metallb
  - https://github.com/bitnami/bitnami-docker-metallb
  - https://metallb.universe.tf
maintainers:
  - name: cellebyte
    email: cellebyte@gmail.com
  - name: Bitnami
    email: containers@bitnami.com
annotations:
  category: Infrastructure

dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
